### ISSUE TITLE
Gear DPS sorting is failing intermittently

### ISSUE THREAD

**Issue by mku1tra** [GuybrushGit/WarriorSim#104]
I have recently noticed that item sorting, when using the Gear DPS option, is failing. This appears to happen intermittently but is easily reproducible from FF and Chrome.

![image](https://github.com/GuybrushGit/WarriorSim/assets/9649184/05be4e24-9abc-4ee2-bd70-e5f6434e93f8)

Pressing the up and down arrows in the DPS column appears to do nothing at all. 
 
I use the sim about once per week and just started experiencing this issue today.  This issue was not occurring before the addition of resistances.

**Comment by Zebouski** [comment]
Yep I found the new Resist gear implementation didn't take into account the hardcoded column IDs that are used to find out which column to sort. The dev who added the resist thing is working on a fix
