### ISSUE TITLE
SoD branch broke the classic era sim

### ISSUE THREAD

**Issue by aastrand** [GuybrushGit/WarriorSim#125]
See:
![image](https://github.com/GuybrushGit/WarriorSim/assets/642148/9bf3757e-4a34-4a9e-b9d3-0549956956c5)

Should be an easy fix?

**Comment by ajohnson-ventera** [comment]
add `classic.html` to the end of the normal url for now. see: https://guybrushgit.github.io/WarriorSim/classic.html

**Comment by GuybrushGit** [comment]
thanks for the warning fixed the links
