### ISSUE TITLE
Rend duration appears to be wrongly set to 10 seconds

### ISSUE THREAD

**Issue by Bananenbrei** [GuybrushGit/WarriorSim#126]
The data strings for Rend within "spells.min.js" appear to be wrong.
The duration for _all_ Rends is set to 10 seconds.

Example for Rank3 Rend:
{id:6547,name:"Rend",classname:"Rend",iconname:"ability_gouge",minlevel:20,maxlevel:29,value1:45,**duration:10**,durationactive:!0,active:!1,aura:!0}

This should be 15
https://www.wowhead.com/classic/spell=6547/rend

**Comment by GuybrushGit** [comment]
Thanks, fixed it for all ranks.
