### ISSUE TITLE
AP in SoD isn't correct

### ISSUE THREAD

**Issue by XOSexyCutie** [GuybrushGit/WarriorSim#130]
I haven't fully figured out what is happening, but it appears like the attack power amount is nearly double what it should be for a SoD warrior? Or maybe just adding an extra 300 some AP. Is it defaulting to level 60 base stats?

**Comment by GuybrushGit** [comment]
Thanks for the warning. It was using level 60 base ap yes.
I think its fixed now but the difference is only 100 not 300 AP.
