### ISSUE TITLE
Rage Calculation for Season of Discovery?

### ISSUE THREAD

**Issue by warriorsimp** [GuybrushGit/WarriorSim#139]
when running consumed by rage itll always have a >90% uptime using any runes even if you dont put any restrictions on heroic strike as the only spender. I think its not taking into account armor values of the average unit of that level and therefore not reducing the rage generated by the decreased weapon damage so its assuming your always rage capped even with faster weapons.

**Comment by GuybrushGit** [comment]
Armor is being taken into account. You probably have CBR set to not use rage below 80 so it keeps refreshing.
