### ISSUE TITLE
Option to use average damage to reduce variance

### ISSUE THREAD

**Issue by larsbratholm** [GuybrushGit/WarriorSim#14]
Right now the weapon damage is sampled uniformly, which enables us to get the variance in DPS we can expect on a fight. However, when comparing gear it would be helpful to have the option to use the average damage on each weapon hit instead, as this reduces the variance meaning that we can get away with fewer simulated runs.

**Comment by GuybrushGit** [comment]
Added an option for it. Variance still seems pretty high tho.
