### ISSUE TITLE
Suggestion: Adjustable rage gain every 2s to simulate tanking

### ISSUE THREAD

**Issue by andersonjohnf** [GuybrushGit/WarriorSim#140]
This is a fantastic tool, but it would be great if you added an adjustable rage gain every 2s to simulate tanking. A lot of rotations function very differently given the additional rage gain from boss damage, and every tank I know uses this tool to sim their DPS.

**Comment by GuybrushGit** [comment]
Added some settings for this.

**Comment by andersonjohnf** [comment]
This is perfect, thank you so much for taking the feedback and implementing it in an even better way that I had pictured. Thanks!
