### ISSUE TITLE
Sim inaccuracy for classic version

### ISSUE THREAD

**Issue by tarwy1** [GuybrushGit/WarriorSim#141]
The classic version of the sim (i.e. vanilla) seems to be responding non-sensically and just wrong in the case of many weapons
![image](https://github.com/GuybrushGit/WarriorSim/assets/38536921/d7e3e462-dd09-439c-8e85-14cd1dad3662)
As you can see in this image (simmed offhand with bwl bis vs a lvl 60 target) the sim seems to be wrong on certain items, for instance mirah's song simming higher than BQWH - I have noticed this as a recent behaviour, so perhaps a feature relating to the SOD version of the sim has impacted the classic version
![image](https://github.com/GuybrushGit/WarriorSim/assets/38536921/0f66f9b8-3263-42d6-af22-97da0cf52ddc)
even if i sim vs a level 63 target, the sim seems to over-value weapon speed in offhand much more than it ever did. note also that i have CTS in mainhand and maladath is way far down on the list, the sim used to put mala right up at the top vs level 63 due to the weapon skill bonus to mainhand

**Comment by GuybrushGit** [comment]
Its because of SoD deep wounds.
On classic does it still get constantly pushed off or have they removed the debuff limit?
I've disabled it on classic meanwhile, can you check if the results make sense now?

**Comment by tarwy1** [comment]
Yep, does seem to be behaving normally now
