### ISSUE TITLE
on use trinkets

### ISSUE THREAD

**Issue by xconcro** [GuybrushGit/WarriorSim#153]
on use trinkets are not simming correctly, the proc or use effect doesnt seem to be implemented. for era.

**Comment by shashaty** [comment]
+1, I noticed this too

**Comment by GuybrushGit** [comment]
I have recently added the item on use effects to the rotation settings, they're working but you need to enable them on the settings.  
I need to try and make it so they're enabled by default.

**Comment by xconcro** [comment]
I don't want to be that guy but I don't see the option for on use effects in the rotation settings or settings in general.
![Screenshot 2024-02-08 152708](https://github.com/GuybrushGit/WarriorSim/assets/159363875/849a12e5-8f0f-42a3-b431-2128af5d5e10)

**Comment by GuybrushGit** [comment]
Do you have any trinkets selected?

**Comment by xconcro** [comment]
Understood now, was hoping it was a setting like previously that I could sim my none on-use trinkets against.

**Comment by GuybrushGit** [comment]
Yes I just changed it to select them by default on the sheet.
