### ISSUE TITLE
[BUG] Slam doesn't reset swing timer even without any Slam runes equipped

### ISSUE THREAD

**Issue by TheGroxEmpire** [GuybrushGit/WarriorSim#156]
As the log below shows, the swing timer is not reset after hard cast slam was done.

<details> <summary> Profile config </summary>

``eyJsZXZlbCI6IjQwIiwicmFjZSI6Ikh1bWFuIiwic2ltdWxhdGlvbnMiOiIxIiwidGltZXNlY3NtaW4iOiI2MCIsInRpbWVzZWNzbWF4IjoiNzAiLCJleGVjdXRlcGVyYyI6IjIwIiwic3RhcnRyYWdlIjoiNzAiLCJ0YXJnZXRsZXZlbCI6IjQyIiwidGFyZ2V0YXJtb3IiOiIxMTIiLCJ0YXJnZXRyZXNpc3RhbmNlIjoiMjUiLCJ0YXJnZXRzcGVlZCI6IjAiLCJ0YXJnZXRtaW5kbWciOiIyMDAiLCJ0YXJnZXRtYXhkbWciOiIzMDAiLCJhZGphY2VudCI6IjAiLCJhcWJvb2tzIjoiTm8iLCJyZWFjdGlvbm1pbiI6IjIwMCIsInJlYWN0aW9ubWF4IjoiMzAwIiwiYmF0Y2hpbmciOiIxMCIsImJsZWVkaW1tdW5lIjoiTm8iLCJhcm1vcnByb2NzIjoiTm8iLCJwcm9maWxlbmFtZSI6IlNsYW0gU3BhbSIsImJ1ZmZzIjpbbnVsbCwiMjQ1OCIsIjExNTQ5IiwiMTcwMDciLCI4OTA3IiwiMTcwNTUiLCIxOTUwNiIsIjQwOTU4MCIsIjgxNjEiLCI0MDc5OTUiLCI4OTQ5IiwiNDQyNiIsIjIzNzY4IiwiNDM4NTM2IiwiMjIyMzciXSwidGFsZW50cyI6W3sibiI6IkFybXMiLCJ0IjpbMywwLDMsMCw1LDAsMiwxLDMsNSwyLDUsMSwwLDAsMCwwLDFdfSx7Im4iOiJGdXJ5IiwidCI6WzAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMF19LHsibiI6IlByb3RlY3Rpb24iLCJ0IjpbMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwXX1dLCJnZWFyIjp7ImhlYWQiOjIxNTE2MSwibmVjayI6MjEzMzQ0LCJzaG91bGRlciI6MjEzMzA0LCJiYWNrIjoyMTMzMDcsImNoZXN0IjoyMTMzMTMsIndyaXN0IjoxOTU5MCwiaGFuZHMiOjIxMzMxOSwid2Fpc3QiOjIxNTM4MCwibGVncyI6MjEzMzMyLCJmZWV0Ijo5NjM3LCJmaW5nZXIxIjoxOTUxMiwiZmluZ2VyMiI6MjEzMjg0LCJ0cmlua2V0MSI6MjEzMzQ4LCJ0cmlua2V0MiI6MjExNDQ5LCJyYW5nZWQiOjk0MjYsInR3b2hhbmQiOjk0MjV9LCJyb3RhdGlvbiI6W3siaWQiOjI2ODcsImZsYWdlbGxhdGlvbiI6dHJ1ZSwiY29uc3VtZWRyYWdlIjpmYWxzZX0seyJpZCI6MjA2NjB9LHsiaWQiOjE4NDk5LCJmbGFnZWxsYXRpb24iOnRydWUsImNvbnN1bWVkcmFnZSI6ZmFsc2V9LHsiaWQiOjE2ODAsIm1pbnJhZ2UiOiI4MCIsIm1pbnJhZ2VhY3RpdmUiOmZhbHNlLCJtYWluY2QiOiIxLjUiLCJtYWluY2RhY3RpdmUiOmZhbHNlfSx7ImlkIjoxMjI5NCwibWlucmFnZSI6IjgwIiwibWlucmFnZWFjdGl2ZSI6ZmFsc2V9LHsiaWQiOjY2MTMsInRpbWV0b2VuZCI6IjEwIiwidGltZXRvZW5kYWN0aXZlIjp0cnVlLCJ0aW1ldG9zdGFydCI6MCwidGltZXRvc3RhcnRhY3RpdmUiOmZhbHNlfSx7ImlkIjo4ODIwLCJtaW5yYWdlIjoiODAiLCJtaW5yYWdlYWN0aXZlIjp0cnVlLCJtYWluY2QiOiIxLjUiLCJtYWluY2RhY3RpdmUiOnRydWUsImJsb29kc3VyZ2UiOmZhbHNlLCJzd2luZ3Jlc2V0IjpmYWxzZSwiYWZ0ZXJzd2luZyI6ZmFsc2V9LHsiaWQiOjQyNTQxOCwicHJvY2Jsb2NrIjp0cnVlLCJyYWdlYmxvY2siOiI2MCIsInJhZ2VibG9ja2FjdGl2ZSI6dHJ1ZSwiZXhlY3V0ZXN0YWNrcyI6IjMiLCJleGVjdXRlc3RhY2tzYWN0aXZlIjpmYWxzZX0seyJpZCI6MjEzMzQ4LCJ0aW1ldG9lbmQiOiIzMiIsInRpbWV0b2VuZGFjdGl2ZSI6dHJ1ZSwidGltZXRvc3RhcnQiOjAsInRpbWV0b3N0YXJ0YWN0aXZlIjpmYWxzZX0seyJpZCI6MjE1MTYxLCJ0aW1ldG9lbmQiOiIxMiIsInRpbWV0b2VuZGFjdGl2ZSI6dHJ1ZSwidGltZXRvc3RhcnQiOjAsInRpbWV0b3N0YXJ0YWN0aXZlIjpmYWxzZX1dLCJydW5lcyI6eyJjaGVzdCI6NDAyODc3LCJsZWdzIjo0MjU0MTgsImhhbmRzIjo0MDMyMTgsImZlZXQiOjQwMjkxM30sImVuY2hhbnQiOnsidHdvaGFuZCI6WzEzNjk1XSwiYmFjayI6WzEzODgyXSwiY2hlc3QiOlsxMzcwMF0sIndyaXN0IjpbMTM2NjFdLCJoYW5kcyI6WzEzODg3XSwiZmVldCI6WzEzNjM3XX19``

</details>

![image](https://github.com/GuybrushGit/WarriorSim/assets/47816228/b3e0e8f5-b6af-4239-b39e-206686b3a521)

**Comment by GuybrushGit** [comment]
Yes I left it up to the "Reset swing" option since we didn't know if it would reset or not.

**Comment by TheGroxEmpire** [comment]
Regular hard casted slam still reset swing timer. Slam with Precision Timing or Bloodsurge procs will be instant and therefore not reset swing timer.
