### ISSUE TITLE
Heroic strike isn't allowed to queue during GCD

### ISSUE THREAD

**Issue by ragingpastry** [GuybrushGit/WarriorSim#16]
Noticed something a bit strange earlier. When using Essence of the Red I didn't see a major decrease in the amount of MH attacks or increase in the amount of Heroic strikes. This led me down a path which ended up here.

I believe that heroic strike isn't being allowed to be queued during GCD as seen here:
https://github.com/GuybrushGit/WarriorSim/blob/a96ffc30e3d57935d85e3602266aabf3970b8c63/dist/js/classes/simulation.js#L78
https://github.com/GuybrushGit/WarriorSim/blob/a96ffc30e3d57935d85e3602266aabf3970b8c63/dist/js/classes/simulation.js#L141

I have opened a PR which addresses this issue.

**Comment by GuybrushGit** [comment]
You're right but this change is not enough I need to do some reworking on this to get proper heroic strikes.

**Comment by GuybrushGit** [comment]
Just pushed a huge rewrite of the simulator core, should fix all issues with skill usage.
