### ISSUE TITLE
Current version

### ISSUE THREAD

**Issue by xconcro** [GuybrushGit/WarriorSim#161]
Bizarre results in recent update. Turned all off wbuffs and simming 400ish dps with almost best in slot gear. Also has a target base armour for season of discovery in era.
![image](https://github.com/GuybrushGit/WarriorSim/assets/159363875/b7ff7459-78c7-4033-b59b-7c464fc4658b)

**Comment by Aga21xd** [comment]
I got the exact same thing, looks like SOD options have been mixed with Era somehow

**Comment by GuybrushGit** [comment]
You have to select armor debuffs now in the settings, sunder etc
