### ISSUE TITLE
Cobrahn's Grasp not in the item list

### ISSUE THREAD

**Issue by JensGM** [GuybrushGit/WarriorSim#162]
Hey,

I can't find Cobrahn's Grasp in the item list for waist

**Comment by GuybrushGit** [comment]
Its too low level so its below the threshold for level 40s

**Comment by JensGM** [comment]
It's better than most items in the list though, for season of discovery

**Comment by GuybrushGit** [comment]
I know but if I lower the threshold the lists get way too large.
Increased Cobrahn's level instead so it should be there now.
