### ISSUE TITLE
A comparison mode?

### ISSUE THREAD

**Issue by JensGM** [GuybrushGit/WarriorSim#163]
I find that I want to try out different item combination when using this tool

It would be great with a mode where i can compare item loadouts, or even brute-forcing through an item list for different slots to find the ideal combination. Currently it takes a lot of work to figure out if sacrificing a set bonus is worth it

**Comment by GuybrushGit** [comment]
That's what profiles are for.

**Comment by JensGM** [comment]
You can only view one profile at a time
