### ISSUE TITLE
Missing AQ40 Item + DMF Agility

### ISSUE THREAD

**Issue by asterixdx** [GuybrushGit/WarriorSim#176]
The item "Vek'lor's Gloves of Devastation" are missing from the sim list, with AQ40 available as a sourcing option.

The item is the maximum crit option for warrior (was gonna sim the 78% crit build).

![sim2](https://github.com/GuybrushGit/WarriorSim/assets/170743094/c6890d3e-f521-4d2f-8184-c842c6771400)
![sim1](https://github.com/GuybrushGit/WarriorSim/assets/170743094/eed3f052-89bb-4e2d-b539-7e5ad7692ab4)

Also the option for using 10% agility DMF buff over the 10% damage buff would be awesome.

(also unrelated side note: the proc rate for Misplaced Servo Arm mace from Naxx is much higher than the rate listed on the sim, meaning its insanely undervalued)

Thanks :)

**Comment by GuybrushGit** [comment]
Added the gloves. Not worth adding dmf agi its only like a 1% dmg buff.
idk what the MSA proc rate is no one has sent me any research.
