### ISSUE TITLE
Axe Specialization not counted

### ISSUE THREAD

**Issue by biskopfalk** [GuybrushGit/WarriorSim#186]
Hi,
The Axe Specialization does not apply on the sim, and is also not auto-marked when selecting orc.
Sword works fine (tested 1hand, 2hand on/off), but Axe does nothing (tested 1hand, 2hand on/off).

If you select Human and enable Axe Spec is does work.

**Comment by GuybrushGit** [comment]
Works for me.

**Comment by biskopfalk** [comment]
Tested again and its working - I must have toggled something off previously.
