### ISSUE TITLE
Settings menu not scrollable on small window size

### ISSUE THREAD

**Issue by hardythedrummer** [GuybrushGit/WarriorSim#2]
When I access the settings page on my laptop, the window is not big enough to display everything. The rotation panel overflows into the Gear Filter panel, and the Gear Filter and Talents panels overflow off the window and cannot be accessed.

<img width="1440" alt="Screen Shot 2020-01-17 at 2 22 10 PM" src="https://user-images.githubusercontent.com/1403344/72643645-ca19ea00-3934-11ea-8cca-a678d003d2ed.png">

**Comment by GuybrushGit** [comment]
Fixed
