### ISSUE TITLE
Special Attack Crit Rate lower than White Attack Crit Rate

### ISSUE THREAD

**Issue by Bigmike4470** [GuybrushGit/WarriorSim#20]
When viewing the stats from a simulation, the special Attack Crit Rate is lower than expected, lower than the white crit rate. This was reproduced with and without Elemental Sharpening stones.
![unknown-2](https://user-images.githubusercontent.com/63668067/80944969-95c12100-8d9f-11ea-9755-3a03ad41a320.png)

**Comment by Bigmike4470** [comment]
Nevermind, didn't know crit chance on special attacks was rolled after chance to dodge /shrug

**Comment by Bigmike4470** [comment]
NEVERMIND. Reopening this. Was confirmed recently on FC #dps-tc channel that only Bloodthirst and Execute should be 2-roll melee spells. Heroic Strike and Whirlwind should both be single roll. Currently the sim is treating all special attacks as 2-roll spells.

**Comment by GuybrushGit** [comment]
How was it determined that Heroic Strike and Whirlwind are single roll, did Blizzard say something or is there any testing?
This goes against retail warrior theorycrafting from back in the day.

**Comment by Bigmike4470** [comment]
I'm not entirely sure but here's a link to the discussion, Dhoris weighed in and confirmed that only Shield Slam, Bloodthirst, Revenge, and Execute are melee spells and that all other yellows should be single roll. He linked some logs as evidence.

https://discordapp.com/channels/383596811517952002/383597174815981568/706924794532069459

**Comment by GuybrushGit** [comment]
Fixed thanks.
