### ISSUE TITLE
Suggestion: Wrath 3pc Battle Shout Indicator

### ISSUE THREAD

**Issue by boktai1000** [GuybrushGit/WarriorSim#24]
There should be some better way to show the site lists when you have 3 pieces of Wrath selected, and that if you have Battle Shout selected for buffs, that you are getting the improved version of it.

At the moment, I can't be certain that it's taking this into account because there isn't any sort of indication on the website, and manually checking the code (see below) is leading to me believe it's not something being accounted for.

Additionally, there should be a way to toggle an improved Battle Shout if for example another party member happens to have the 3pc already and you are leaching off of it without having 3pc yourself (or something like putting on the 3pc and popping BS - then swapping gear)

**Spell ID: 23563**

**Sources:**
https://classicdb.ch/?spell=23563 
https://classic.wowhead.com/spell=23563/enhanced-battle-shout

**Other Things To Note:**
This does get multiplied by the Battle Shout talents. I have 5/5 Improved Battle Shout in the Fury tree, which actually makes this go from a 30 AP increase to 37 AP for me.

Rank 6 Battle Shout + 5/5 Improved Battle Shout (no Wrath 3pc) = **241 Attack Power**
![image](https://user-images.githubusercontent.com/9054563/81956395-dc4d2180-95d0-11ea-8db3-45a3cc69bdb0.png)

Rank 6 Battle Shout + 5/5 Improved Battle Shout + Wrath 3pc = **278 Attack Power**
![image](https://user-images.githubusercontent.com/9054563/81956463-f4bd3c00-95d0-11ea-876c-5cf475f4cc7f.png)

**Line of Code:**
https://github.com/GuybrushGit/WarriorSim/blob/e9baeb63effa9dad651058fdf0eb658e956a8e83/js/classes/player.js#L254

Seems it's checking for AQ Books and Imp Battle Shout talent at the moment but nothing else, I could be mistaken though

**Fight Club Spreadsheet:**
Here's how the Fight Club Spreadsheet is handling it currently

![image](https://user-images.githubusercontent.com/9054563/81956063-7eb8d500-95d0-11ea-8ccd-d4668bcb31de.png)

**Comment by GuybrushGit** [comment]
It was there but it was adding just a flat 30 AP with the set.
Fixed it and added it as a buff option.
