### ISSUE TITLE
Badge of the Swarmguard activation is incorrect

### ISSUE THREAD

**Issue by Malefication** [GuybrushGit/WarriorSim#28]
Badge of the Swarmguard is unique as a trinket in the way that it doesn't share an activation cooldown with any other trinkets in the game. This is not accounted for in the warrior sim, which can easily be reproduced by setting the fight to a 60s length and selecting both it and Diamond Flask. Diamond Flask will be up for the entire fight, and the badge won't be up at all.

**Comment by GuybrushGit** [comment]
yea its on my todo list
