### ISSUE TITLE
Haste affecting DPS negatively past a certain point

### ISSUE THREAD

**Issue by budsthewarrior** [GuybrushGit/WarriorSim#29]
With full world buffs and horde side I was testing some AQ gear sets and came across a weird error.

AP 2195
Strength 598
Agi 263
Hit 12%
Skill 305/305
Crit 41.35%
Crit cap 41.20%
Dmg 100% 62.5%

Sim #1 115% haste, 250k sims, 70-90 sec fight
1451 dps

Sim #2 116.15% haste (minor haste to gloves) 
1455 dps

Sim #3 117.31% haste (haste to gloves/legs)
1459 dps

Sim #4 118.48% haste (haste to all 3 options)
1447 dps

In all cases where I wasn't using the haste enchant I had selected the strength enchant in it's place.
It doesn't matter which of the 3 haste enchants, having 1 or 2 is a dps gain, and having all 3 is a loss.

**Comment by GuybrushGit** [comment]
You sure you didn't change anything else?
Did some testing as an Orc with full buffs:
All 3 str: 1182.92
1 haste: 1187.66
2 haste: 1188.13
3 haste: 1192.74

**Comment by budsthewarrior** [comment]
I didn't change anything else, but I was stacking the 3 haste enchants with
WCB haste.
