### ISSUE TITLE
Suggestion: Add Slam

### ISSUE THREAD

**Issue by Mansillajb** [GuybrushGit/WarriorSim#38]
Could you add Slam logic to the sim for the 2H warriors out there, please?

**Comment by Lbniese** [comment]
Slam is worse than the default hamstring 2H logic as horde and 2h is useless for alliance players.
This tool is to some extend built for minmaxing which is why it would make no sense to add Slam logic to be honest.

**Comment by Mansillajb** [comment]
> Slam is worse than the default hamstring 2H logic as horde and 2h is useless for alliance players.
> This tool is to some extend built for minmaxing which is why it would make no sense to add Slam logic to be honest.

Thank you for taking the time to reply to the suggestion, I've used two other sims that allowed slam to be simed, and they both showcased a DPS improvement over hamstring spam. I would love to hamstring spam and not have to worry about clipping attacks. Do you by any chance have some resources that back up this info? I want to make sure I fully understand the benefits before moving forward.
