### ISSUE TITLE
Suggestion: Import/Export Gear

### ISSUE THREAD

**Issue by ragingpastry** [GuybrushGit/WarriorSim#4]
I'm not sure how feasible this is, but it would be really nice to be able to import and export gear options.

I have a lot of combinations of gear that I sim and I currently have to track that in a spreadsheet manually. It would be nice to be able to export the gear and results used for a sim, along with information on the sim settings.

Exporting could be useful for sharing simmed gearsets

**Comment by trolando** [comment]
Maybe a feature to import/export current choices/settings to/frrom a JSON string would work for this?
