### ISSUE TITLE
Haste capped at 200%?

### ISSUE THREAD

**Issue by Suyer** [GuybrushGit/WarriorSim#45]
Your code caps haste at 200% -- why?

You run into the problem where this is reached quite easily if you are a troll.  (Note the other open issue describing a problem where the 3rd haste enchant drops dps -- this is potentially explained by this cap causing the 3rd enchant to be useless).

For example:
WCB = 15%
Flurry = 30%
Troll(max) = 30%
Gloves = 1%
Head = 1%
Pants = 1%

1x1.15x1.3x1.3x1.01x1.01x1.01 = 2.002
Note that without the 3rd haste enchant you're at 1.982

As far as I am aware there is no cap to haste in game.

Other possible haste buffs:
Chicken = 5%
Juju Flurry = 5%
Counterweight = 3%
MCP = 50%

**Comment by GuybrushGit** [comment]
Fixed ty
