### ISSUE TITLE
Soulrender missing from OH options

### ISSUE THREAD

**Issue by chrispphillips** [GuybrushGit/WarriorSim#47]
I'm trying to run sims with Soulrender in my OH but it's not available to select from. Could you please add it? Thanks!

**Comment by lutzklai** [comment]
Soulrender for offhand is mis-listed as phase 5. So if you turn on phase 5 in the settings you'll see soulrender. I've made a PR to align the phases https://github.com/GuybrushGit/WarriorSim/pull/50
