### ISSUE TITLE
Strength worth 2.2 attack power without kings or zg.

### ISSUE THREAD

**Issue by Kaladryn** [GuybrushGit/WarriorSim#49]
Using the custom tab, I am consistently getting Strength worth 2.2 Attack Power WITHOUT Kings or ZG buff selected. Unless I'm missing something, this doesn't seem possible.

**Comment by lutzklai** [comment]
I'm not able to reproduce this. Do you have any other buffs or set bonuses that might be causing this?

**Comment by Kaladryn** [comment]
I repeated several of the tests I did yesterday and also cannot repeat the bug. 1str=2.0 ap without and 2.2 with exactly.
BTW yesterday I was showing 2.4 with kings and 2.2 without. Sorry for the false alarm, if I can reproduce the bug I will let you know.
Thank you, really sweet tool, the best of all the warrior sims.
