### ISSUE TITLE
Suggestion: Add furysim-like logging and reporting

### ISSUE THREAD

**Issue by ragingpastry** [GuybrushGit/WarriorSim#5]
It would be nice to see things like average hit/crit of abilities as well as a full simulation event log. This simulation event log would be a events-based view of casts, damage and rage gain. I think this is the one main feature that this sim is missing that would put it over the top.

I'm trying to compare the differences in results that I get when using FurySim and GuyBrush. I think being able to compare the sim logs (avg damage of abilities, event based view) would go a long way

**Comment by GuybrushGit** [comment]
Just added something like this for my own debugging purposes but its comented out in the live version, all the "if (log)" checks caused a slowdown in the simulations even with log set to false.  
If you want to debug it download the code, uncomment those lines, set log to true and check the JS console.
