### ISSUE TITLE
Suggestion: have savable profiles with different setting configurations

### ISSUE THREAD

**Issue by IsaacSmith13** [GuybrushGit/WarriorSim#52]
With AQ out now, keeping world buffs is virtually impossible, but I'd still like to see how I perform with buffs on for BWL.

Having the ability to save profiles so that I could make one with world buffs and one without would save a lot of time. Currently, I would have to sim the different gear options for every slot with each configuration two times and record the results of the first buff status so I don't lose them when I switch to the second.

**Comment by GuybrushGit** [comment]
Yeah would be cool but I don't have time to make this. If anyone wants to do it go ahead.
