### ISSUE TITLE
"AQ Books" option doesn't update Totems or Blessing of Might

### ISSUE THREAD

**Issue by chrisbadger** [GuybrushGit/WarriorSim#55]
Selecting "AQ Books: Yes" updates battle shout (and presumably HS, too), but does not seem to update Blessing of Might, Grace of Air Totem, or Strength of Earth Totem.

I tested by disabling all buffs except for one of the above, checking my AP/Str/Agi in the panel, and then toggling the AQ Book option.  None of the values in the panel changed.

**Comment by chrisbadger** [comment]
For reference (assuming no relevant talents on the person doing the buffing)
* [Strength of Earth Totem (Rank 5)](https://classic.wowhead.com/spell=25361/strength-of-earth-totem) gives 77 strength (16 more than Rank 4).
* [Grace of Air Totem (Rank 3)](https://classic.wowhead.com/spell=25359/grace-of-air-totem) gives 77 agility (10 more than Rank 2)
* [Blessing of Might (Rank 7)](https://classic.wowhead.com/spell=25291/blessing-of-might) gives 185 AP (30 more than Rank 6).

**Comment by GuybrushGit** [comment]
Fixed
