### ISSUE TITLE
bug: Zulian hacker adding weapon skill twice

### ISSUE THREAD

**Issue by ragingpastry** [GuybrushGit/WarriorSim#6]
When Zulian Hacker is selected it appears to add the weapon skill twice.

For example, when Zulian Hacker is chosen for MH you can observe weapon skill being increased by +4 instead of +2.

Additionally, when browsing away from the MH tab and coming back, both Zulian Hacker options appear to be selected. I think what is actually happening is Zulian Hacker is being added twice to the Player.

Still have to look more into this, but wanted to make an issue so that I remember / others can investigate.

**Comment by ragingpastry** [comment]
Pretty sure its because of this line
https://github.com/GuybrushGit/WarriorSim/blob/dd03f7f6e1d0b605c77f9761b3445eb5ecead6b8/dist/js/ui.js#L250

The zulian hackers have the same item ID, so its being selected twice

**Comment by GuybrushGit** [comment]
Fixed
