### ISSUE TITLE
mind if i help with Chinese version of this sim?

### ISSUE THREAD

**Issue by eggerr** [GuybrushGit/WarriorSim#66]
I have 2 warriors, in US and China server, i like your sim very much, helps a lot, great job man!
when i introduce this to my friends in China, they have trouble with connections, sometimes github will be blocked by GFW. Also they have problem with English too. So I'm thinking maybe i can help with Chinese version of your sim, and make a mirror server in China, to let them access faster. is that OK?

**Comment by GuybrushGit** [comment]
sure
