### ISSUE TITLE
Suggestion: use trinket at beginning of fight

### ISSUE THREAD

**Issue by Kaladryn** [GuybrushGit/WarriorSim#68]
Trinkets such as Eathstrike can be used back to back with trinkets such as Diamond Flask on mid to long fights, at option to use Earthstrike at the beginning of the fight might make trinket options easier to sim. Just a suggestion if it's not too difficult.

**Comment by ups1dedomn** [comment]
Following is not really relevant to the problem, but the game: Using either ES or DF puts both on 2m cd, so there is no point in having both equipped. On fights where you can use ES twice (2 min cd) ES > DF, on fights that are between ~50s to 2 min ES < DF. There is a graph somewhere on the net where you can see exactly when one overtakes the other.

**Comment by Kaladryn** [comment]
I heard this rumor also but it isn't true, using Earthstrike puts Diamond Flask on a 20-second cooldown only. This means you can use ES then immediately use DF as soon as it is over, with no downtime between the two. Everyone in my guild uses them both together frequently, including myself, so I am positive about this fact. Using DF first puts ES on 60second cooldown, so they can be used in reverse order also with no downtime between the two.

**Comment by ups1dedomn** [comment]
Hm. Then I shall try that. Thanks for being polite about my ignorance.

**Comment by d07RiV** [comment]
The sim already chains trinkets in the way you described (ZHM -> Earthstrike -> Jom Gabbar -> Spider -> Slayer -> Cloudkeeper -> DFlask), if the fight is long enough. However, since DFlask is 60 seconds, it takes up the entire fight, so you have to increase fight duration for it to work.

**Comment by Kaladryn** [comment]
Awesome! Thank you!
WarriorSim is the best!!
