### ISSUE TITLE
Add DW tanking as option?

### ISSUE THREAD

**Issue by ups1dedomn** [GuybrushGit/WarriorSim#69]
Would be superb if anyone could add dual wield tanking as an option. This would (at best) have one option. Integer field for incoming damage from boss -> translates to rage gain if hit is not avoided. Alternatively tanks can just assume essence of the red as an approximation. The second and most important difference to the simulation code would be the additional chance to be parried and to be blocked.

Enrage phase can be ignored, as can shield blocking and survivability. Those are outside the scope of a feasible simulation, and commonly understood mechanics to keep in mind when reviewing the results IMO. Lots of discussion in the (horde) guild right now about swapping edgies for annihilation, due to the tanks' ability to spam heroic strike and thus not being glanced. The value of avoidance reduction to the boss is however difficult to evaluate, and to my knowledge no sims do this. The best current option is the spreadsheet on Fight Club discord, which does nothing to demonstrate for example consistency in early threat.

**Comment by d07RiV** [comment]
I fear that falls way out of the scope of the simulator. It's possible, but would be basically a whole new simulator on top of everything. You'd need to model incoming rage in some way - essence of red is one way, but it's not quite accurate on some bosses. Effect of parry haste (for the player) is also impossible to estimate without knowing how often the boss attacks. The timing of consumables/cooldowns is very different - you usually want to pop CDs early to get a threat lead. And it's not clear how "consistency in early threat" would be represented.
