### ISSUE TITLE
Suggestion: Selected items only for 'Gear/Enchant DPS' loop

### ISSUE THREAD

**Issue by theochemtheo** [GuybrushGit/WarriorSim#7]
Thanks a lot for making the sim, really useful!

I've been using the 'Gear DPS' and 'Enchant DPS' buttons to loop through options to make it easier to compare between the pieces, but for long lists (e.g. the weapon list), it starts to take quite a while to loop through. Right now I can use the filters to coarsely remove items, but it would be really helpful to have checkboxes or something like that to more easily select which options I want to compare, to cut down on wasted time.

Cheers!

**Comment by GuybrushGit** [comment]
You can now Show / Hide rows.
