### ISSUE TITLE
Weapon skill no longer counted?

### ISSUE THREAD

**Issue by Hoaas** [GuybrushGit/WarriorSim#75]
I'm a gnome running Expert Goldminer's Helmet, and noticed that very recently (maybe even today, 2020-11-01), it no longer sims as any good at all.

Have recently gotten more hit and crit, so I expected changes, but this seems a bit extreme?
Running with Blessed Qiraj War Axe and Crul'shorukh, Edge of Chaos.  Can post full gear list if needed, all settings if needed. But shouldn't be anything too far from default.

Edit: Edgemaster's seems to be a 55 dps increase, regardless if I have axe skill from Goldminer's Helmet or not.
Edit2: Circlet of Restless Dreams (+6 daggers) also seems to be best for gnomes with axes in the current version. But not any good if using daggers. 🙈

![image](https://user-images.githubusercontent.com/414791/97816280-7b0b2e80-1c94-11eb-86d9-1f5a10bc61f6.png)

**Comment by d07RiV** [comment]
Whoops, misplaced all weapon skills
