### ISSUE TITLE
Stat Str:AP and Agi:CSR weights seem inaccurate

### ISSUE THREAD

**Issue by jdfitzpatrick** [GuybrushGit/WarriorSim#77]
I have run millions of sims on a wide arrangement of gear setups in the Tier 2.5 realm and notice a pattern that Strength frequently outperforms an equivalent raw AP, the same goes for AGI outperforming raw %critt.

Is there an intention for this phenomina to occur to favor the stats that have other non-DPS value (IE AGI gives you dodge)?

![image](https://user-images.githubusercontent.com/13631085/98984402-28c9d900-24f0-11eb-849d-f00ccd48b8cb.png)

Here's a screenshot of the calculated stat weights after 900k simulations. If you multiply Agi (0.76) by 20, we get that 20Agi is worth 15.2 DPS while 1% critt chance is worth just 11.94, or to put another way, Critt chance is being underweighted at about 79% of the value of and equivalent amount of Agility.

Likewise, I'm seeing Strength come out to 1.13 DPS and AP at 0.45 (0.9 normalized to STR) or again about 80% of the raw base stat's value like-for-like.

A good piece of gear to make this observation with is writs: Hive Defiler Wristguards  which have 23 STR (46AP) 18 AGI (0.9% critt) versus the Wristguards of Vengeance which have 24 Str (48AP) and 1% Critt. By all measures the latter should outperform the former in sufficiently high sample counts, however even when running 2 million simulations, I consistently drive the decimal place further, but the gap still remains about 0.6 more DPS in favor of the item with objectively lower stats. Admittadly this is a vanishingly small margin at an overall DPS in the ~1570's but the result is reproducible and seems to contradict the expected values.

To see this phenomena play out in STR:AP, check the comparison of Onslaught Girdle vs Belt of Never-ending Agony.
OG: 1% critt, 1% hit, 31 STR (62AP)
BoNA: 1% critt, 1% hit, 64AP

By all measures, BoNA should have a 2AP advantage, and therefore, in sufficiently high sample counts, should _just_ edge out the OG. Instead I get a massive difference in the order of 6DPS (in the otherwise same gear as the Hive Defiler comparison above), favoring what should be the objectively worse item, Onslaught Girdle.

Does anyone understand why this would be? I looked at player.cpp and I didn't notice anything that would cause this discrepancy...

EDIT: as I type this I'm thinking the difference may just be in Blessing of Kings providing a stat boost to the raw stats but not providing this boost to the derived stats.

**Comment by jdfitzpatrick** [comment]
It turns out BOK is indeed the culprit, I feel like typing the above comment was necessary for me to realize this. Thanks for making a great tool.

**Comment by d07RiV** [comment]
Yep, you can notice that agility and str don't even run a separate simulation, their weights appear at the same time as AP and crit because the conversion rate is known (unless using blood fury, in which case str runs a separate sim).
