### ISSUE TITLE
Simulation Randomly Stops

### ISSUE THREAD

**Issue by wlfbck** [GuybrushGit/WarriorSim#80]
See this screenshot as an example:
![grafik](https://user-images.githubusercontent.com/1621804/101980533-65f7c700-3c66-11eb-99b9-3716b1eaba77.png)

This has been happening for a while now and often. Only solution is to f5 and click "gear dps" again.

Using Firefox 83.

**Comment by Zebouski** [comment]
Fixed in https://github.com/GuybrushGit/WarriorSim/pull/112
