### ISSUE TITLE
Crit chance

### ISSUE THREAD

**Issue by DivineDivan** [GuybrushGit/WarriorSim#84]
Got problem with critchance.

Work with https://guybrushgit.github.io/WarriorSim/

Naked dwarf in berserker stance with only Deathbringer has 7% of crit according to sim.
But game sayes it is 11,8%

![warriorsim](https://user-images.githubusercontent.com/22323954/104942385-6ef65980-59c5-11eb-80a5-c1f66d40558d.jpg)

![wowcrit](https://user-images.githubusercontent.com/22323954/104942290-4ff7c780-59c5-11eb-8334-d8ae854c8321.jpg)

**Comment by d07RiV** [comment]
This is due to crit suppression, you have 4.8% reduced crit chance against level 63 targets.
