### ISSUE TITLE
2 easily bought items missing from the item list

### ISSUE THREAD

**Issue by armoredc** [GuybrushGit/WarriorSim#85]
Gurubashi Helm and Thick Obsidian Breastplate are 2 items available on the AH and very good for warriors, therefore I ask if they can be added.

Here are the items.cpp lines that need to be changed in order for that to happen:

  {  20263, {  13,  22,  21,   0, 0, 0,  549,  0, 0, 0, { 0, 0, 0, 0, 0, 0 } }, { -1,   0,   0, 0.0 }, {   0, 0.0, 0,   0,   0, 0, 0, 0, nullptr              } }, // Gurubashi Helm
  
    {  22196, {  16,  38,   0,   0, 0, 0,  814,  0, 0, 0, { 0, 0, 0, 0, 0, 0 } }, { -1,   0,   0, 0.0 }, {   0, 0.0, 0,   0,   0, 0, 0, 0, nullptr              } }, // Thick Obsidian Breastplate

**Comment by d07RiV** [comment]
Added both.
