### ISSUE TITLE
BT during execute behaving weird

### ISSUE THREAD

**Issue by ohganot** [GuybrushGit/WarriorSim#86]
If you set the sim to use BT when you have lets say 10000 AP (which you never do), it still sims higher than when you leave BT during execute option untoggled. Doesn't make sense, since it should sim the same dps since you're not using BT in both cases.
Made me abit suspicious of the BT during execute option.

**Comment by d07RiV** [comment]
There's no BT during execute toggle, only the AP threshold. If you're removing this checkbox, you're disabling executes altogether, which would explain the DPS loss.

![image](https://user-images.githubusercontent.com/3448203/118545126-d9928880-b75e-11eb-8055-64f0b8c20276.png)
