### ISSUE TITLE
MH Crit Cap calculated with OH hit chance

### ISSUE THREAD

**Issue by Joferk** [GuybrushGit/WarriorSim#87]
It looks like the MH critcap in the sidebar is calculated using the OH miss chance value.
I am a human warrior using swords (so 305 weapon skill) with 8% hit. MH miss chance is 0% and chance to get dodged is 6%.
Crit cap = 100% - 40% (glancing blows) - 0% (chance to miss) - 6% (chance to get dodged) = 54%
Sidebar is showing MH crit cap as 37.20%, same as OH. That alignes with using the OH miss chance of 24.8% for MH
OH Crit cap = 100% - 40% (glancing blows) - (24.8% - 8%) (chance to miss) - 6% (chance to get dodged) = 37.2%

Am i missing something here?

Source used for numbers: https://forums.askmrrobot.com/t/hit-rating-and-hit-caps-in-wow-classic/8614

**Comment by Kaladryn** [comment]
Are you assuming heroic strike mainhand? You said, "MH miss chance is 0%" that is incorrect, mainhand and offhand miss chance is the same for white hits. I think this can be closed.

**Comment by d07RiV** [comment]
^ this

Dual wield penalty applies to both weapons, there's no difference between MH and OH hit chance.
